# Generated by Django 4.2.7 on 2023-11-23 06:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("user", "object_id")},
        ),
    ]
